name: Trigger VSPO Live Status Check

on:
  schedule:
    - cron: '*/6 * * * *'
  workflow_dispatch:

jobs:
  trigger_live:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Live Check (Smart Interval)
        run: curl -X GET "https://vspo-proxy-git-main-renas-projects-c8ce958b.vercel.app/api/youtube?no_increment=true&password=${{ secrets.CRON_SECRET }}"
