name: Trigger Vercel Data Update

on:
  schedule:
    - cron: '*/21 * * * *'
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger CN Update
        run: curl -X GET "https://vspo-proxy-git-main-renas-projects-c8ce958b.vercel.app/api/youtube?force_refresh=true&password=${{ secrets.CRON_SECRET }}"
      
      - name: Trigger JP Update
        run: curl -X GET "https://vspo-proxy-git-main-renas-projects-c8ce958b.vercel.app/api/youtube?force_refresh=true&lang=jp&password=${{ secrets.CRON_SECRET }}"